version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == worker
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    image: php:fpm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == worker
    volumes:
      - ./php:/var/www/html
    command: ["php", "-S", "0.0.0.0:9000", "-t", "/var/www/html"] #to test

  mysql:
    image: mysql:5.7
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == manager
    environment:
      MYSQL_ROOT_PASSWORD: Etml123456789
      MYSQL_DATABASE: telegraph
    ports:
      - "3306:3306"

networks:
  default:
    driver: overlay

#docker node update --label-add role=worker <worker1_id>
#docker node update --label-add role=worker <worker2_id>
#docker node update --label-add role=worker <worker3_id>
#docker node update --label-add role=manager <manager1_id>

#docker stack deploy -c docker-compose.yaml your_stack_name