version: '3.8'

services:
  php:
    build:
      context: ./serveur_php
      dockerfile: php.dockerfile
    container_name: php_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./serveur_php/html:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: ${DB_ROOTPASSWORD}
      DB_PASSWORD: ${DB_ROOTPASSWORD}
      DB_NAME: ${GETSAVEMESSAGE_DBNAME}


  db:
    image: mysql:8.0.30
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - ./serveur_mysql/setup_telegraph_db.sql:/docker-entrypoint-initdb.d/1.sql 
      - dbdata:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

  web:
    build:
      context: ./client
    restart: always
    ports:
      - "8085:80"


volumes:
  dbdata:
