# Creation date: 19.08.2024
# Created by: CSR
# Description (quelques indices): 
# Le service PHP utilise nativement le port 80, ce port 80 est exposé sur le port 8080 de l'hôte.
# Le nom du conteneur sera php_container
# Le build sera fait en utilisant le fichier php.dockerfile

version: '3.8'

services:

  php:
    build:
      context: ./serveur_php
      dockerfile: php.dockerfile
    container_name: php_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:8.0.30
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - ./serveur_mysql/setup_telegraph_db.sql:/docker-entrypoint-initdb.d/1.sql 
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_container
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

  web:
    build:
      context: ./client
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8085:80"

# The database will be persistent among container restarts.
volumes:
  dbdata:
